// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sequence.proto

package com.sqlpy.demo.rpcs;

public final class Sequence {
  private Sequence() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SequenceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SequenceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SequenceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SequenceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016sequence.proto\"1\n\017SequenceRequest\022\023\n\006o" +
      "ffset\030\001 \001(\003H\000\210\001\001B\t\n\007_offset\"$\n\020SequenceR" +
      "esponse\022\020\n\010sequence\030\001 \001(\0032>\n\016SequenceSer" +
      "ver\022,\n\003get\022\020.SequenceRequest\032\021.SequenceR" +
      "esponse\"\000B\027\n\023com.sqlpy.demo.rpcsP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SequenceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SequenceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SequenceRequest_descriptor,
        new java.lang.String[] { "Offset", "Offset", });
    internal_static_SequenceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SequenceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SequenceResponse_descriptor,
        new java.lang.String[] { "Sequence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
