// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sequence.proto

package com.sqlpy.demo.rpcs;

public interface SequenceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SequenceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sequence = 1;</code>
   * @return The sequence.
   */
  long getSequence();
}
