// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sequence.proto

package com.sqlpy.demo.rpcs;

public interface SequenceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SequenceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 只有在客户端想要重新设置偏移量时才填写 offset 的值
   * </pre>
   *
   * <code>optional int64 offset = 1;</code>
   * @return Whether the offset field is set.
   */
  boolean hasOffset();
  /**
   * <pre>
   * 只有在客户端想要重新设置偏移量时才填写 offset 的值
   * </pre>
   *
   * <code>optional int64 offset = 1;</code>
   * @return The offset.
   */
  long getOffset();
}
